# Employee Database Analysis
Name: CHANDU BABU
Student ID:iitp_aimlt_2601840
.

In [1]:
import sqlite3
import random
import pandas as pd

In [2]:
# Create connection
conn = sqlite3.connect("employees.db")
cursor = conn.cursor()

# Create table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary REAL,
    years_experience INTEGER,
    performance_score REAL
)
""")

departments = ["Engineering", "Sales", "Marketing", "HR", "Finance"]

# Generate 40 employee records
employees = []

for i in range(1, 41):
    name = f"Employee_{i}"
    department = random.choice(departments)
    salary = random.randint(50000,150000)
    years_experience = random.randint(1,15)
    performance_score = round(random.uniform(1.0,5.0),2)

    employees.append((i,name,department,salary,years_experience,performance_score))

# Insert data
cursor.executemany("""
INSERT INTO employees
(emp_id,name,department,salary,years_experience,performance_score)
VALUES (?,?,?,?,?,?)
""", employees)

conn.commit()

print("Database created with 40 employee records.")

Database created with 40 employee records.

In [3]:
query1 = """
SELECT name, department, salary, performance_score
FROM employees
WHERE performance_score >= 4.0
AND years_experience >= 3
ORDER BY performance_score DESC
LIMIT 15
"""

df_q1 = pd.read_sql_query(query1, conn)
df_q1

          name   department    salary  performance_score
0  Employee_40    Marketing   54648.0               4.96
1  Employee_27  Engineering  110513.0               4.72
2  Employee_24        Sales   58455.0               4.67
3  Employee_29      Finance  134194.0               4.54
4   Employee_2           HR  148778.0               4.40
5  Employee_26      Finance  145263.0               4.30
6  Employee_25        Sales   82684.0               4.29
7  Employee_33    Marketing   85856.0               4.25
8  Employee_11    Marketing  118011.0               4.16
9  Employee_35  Engineering   55288.0               4.04

In [4]:
query2 = """
SELECT *
FROM employees
WHERE salary BETWEEN 70000 AND 110000
AND department IN ('Engineering','Sales')
ORDER BY department, salary DESC
"""

df_q2 = pd.read_sql_query(query2, conn)
df_q2

,emp_id,name,department,salary,years_experience,performance_score
0,10,Employee_10,Engineering,92318.0,5,2.87
1,18,Employee_18,Engineering,87405.0,9,2.76
2,34,Employee_34,Engineering,79032.0,1,1.76
3,21,Employee_21,Engineering,73477.0,7,2.54
4,15,Employee_15,Sales,108153.0,12,2.45
5,25,Employee_25,Sales,82684.0,3,4.29
6,32,Employee_32,Sales,71718.0,6,3.45

In [5]:
query3 = """
SELECT department,
COUNT(*) AS employee_count,
AVG(salary) AS avg_salary
FROM employees
GROUP BY department
ORDER BY avg_salary DESC
"""

df_q3 = pd.read_sql_query(query3, conn)
df_q3

    department  employee_count     avg_salary
0      Finance              12  103175.083333
1    Marketing               9   97715.444444
2           HR               7   94499.428571
3        Sales               5   93952.000000
4  Engineering               7   90519.285714

In [6]:
df_all = pd.read_sql_query("SELECT * FROM employees", conn)

avg_perf = df_all.groupby("department")["performance_score"].mean()

avg_perf

department
Engineering    3.137143
Finance        2.910000
HR             2.124286
Marketing      3.294444
Sales          3.494000
Name: performance_score, dtype: float64

In [7]:
pandas_q1 = (
    df_all
    .loc[(df_all["performance_score"] >= 4.0) & (df_all["years_experience"] >= 3),
         ["name","department","salary","performance_score"]]
    .sort_values(by="performance_score", ascending=False)
    .head(15)
)

pandas_q1

           name   department    salary  performance_score
39  Employee_40    Marketing   54648.0               4.96
26  Employee_27  Engineering  110513.0               4.72
23  Employee_24        Sales   58455.0               4.67
28  Employee_29      Finance  134194.0               4.54
1    Employee_2           HR  148778.0               4.40
25  Employee_26      Finance  145263.0               4.30
24  Employee_25        Sales   82684.0               4.29
32  Employee_33    Marketing   85856.0               4.25
10  Employee_11    Marketing  118011.0               4.16
34  Employee_35  Engineering   55288.0               4.04

In [8]:
conn.close()

## SQL vs Pandas Comparison

SQL and Pandas are both powerful tools for data analysis but they differ in syntax and typical usage. SQL uses expressions such as `=` for equality, `AND` for combining conditions, and `ORDER BY` for sorting results. In contrast, Pandas uses Python-style syntax such as `==` for equality, `&` for logical AND, and `.sort_values()` for sorting data. SQL queries are typically executed directly on databases, while Pandas operations are performed on DataFrames loaded into memory.

SQL is particularly useful when working with relational databases and structured data stored on disk. It allows analysts to filter, aggregate, and join large datasets efficiently without loading the entire dataset into memory. Pandas, on the other hand, is ideal for in-memory data manipulation, exploratory data analysis, and integration with Python's data science ecosystem such as NumPy, Matplotlib, and Scikit-learn.

For datasets that are too large to fit into memory, SQL is generally the better choice because database engines are optimized for disk-based storage, indexing, and query optimization. Pandas performs best when datasets comfortably fit into RAM and when complex transformations or statistical analysis are required.